#!/bin/bash
#PBS -l nodes=1:ppn=12,walltime=00:15:00
#PBS -q batch
#PBS -N result
#PBS -j oe
#PBS -V

#cat $PBS_NODEFILE
[ -z "$RIPPLE_PROJ" ] && echo "Need to set RIPPLE_PROJ to location fo RippleTank folder" && exit 1;

cd $RIPPLE_PROJ
./ripple.x 50 4 1 >source.dat



